apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  namespace: justeh
  name: helloworld-python
  annotations:
    autoscaling.knative.dev/minScale: "1"
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: helloworld-python
spec:
  source:
    git:
      ref:
        branch: main
      url: https://github.com/justeh/helloworld-python.git
